package customer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Test {

	public static void main(String[] args) throws SQLException {
		try {
			Class.forName("org.hsqldb.jdbc.JDBCDriver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}

		Connection conn = DriverManager.getConnection("jdbc:hsqldb:file:D:/data/customerDB", "SA", "");
		Statement stmt = conn.createStatement();
		
//		create(stmt);
//		insert(stmt);
		print(stmt);
		
		stmt.close();
		conn.close();
	}
	private static void create(Statement stmt) throws SQLException{
		String createSql = "DROP TABLE customer IF EXISTS ;CREATE TABLE customer(ID INTEGER GENERATED BY DEFAULT AS IDENTITY, REALNAME VARCHAR(20),MOBILE VARCHAR(11),EXTRA VARCHAR(255), CREATE_DATE DATE,UPDATE_DATE DATE ,PRIMARY KEY (ID));";
		stmt.execute(createSql);
	}
	
	private static void print(Statement stmt)throws SQLException{
		String querySql="SELECT * FROM customer;";
		ResultSet rs = stmt.executeQuery(querySql);
		while (rs.next()) {
			System.out.println("id: " + rs.getInt("id"));
			System.out.println("name: " + rs.getString("REALNAME"));
		}
		if(rs !=null){
			rs.close();
		}
	}
	private static void insert(Statement stmt)throws SQLException{
		String insertSql = "INSERT INTO customer(ID, REALNAME, CREATE_DATE) VALUES ('2', 'TEST', SYSDATE);";
		stmt.execute(insertSql);
	}
}
