package com.funstill.customer.table.init;

import java.sql.SQLException;

import com.funstill.customer.util.HsqlUtil;

public class BillTable {

	public static void main(String[] args) throws SQLException {
		HsqlUtil hsql = new HsqlUtil();
		String sql = "DROP TABLE bill IF EXISTS ;CREATE TABLE bill(id BIGINT GENERATED BY DEFAULT AS IDENTITY,payable  INTEGER(11),received INTEGER(11),extra VARCHAR(255), create_date TIMESTAMP ,update_date TIMESTAMP ,PRIMARY KEY (id));";
		hsql.getConnection();
		hsql.executeQuery(sql);
		hsql.releaseConn();
	}
}
