package com.funstill.customer.table.init;

import java.sql.SQLException;

import com.funstill.customer.util.HsqlUtil;

public class CustomerTable {

	public static void main(String[] args) throws SQLException {
		HsqlUtil hsql = new HsqlUtil();
		String sql = "DROP TABLE customer IF EXISTS ;CREATE TABLE customer(id BIGINT GENERATED BY DEFAULT AS IDENTITY, realname VARCHAR(20),mobile VARCHAR(11),extra VARCHAR(255), create_date TIMESTAMP ,update_date TIMESTAMP  ,PRIMARY KEY (id));";
		hsql.getConnection();
		hsql.executeQuery(sql);
		hsql.releaseConn();
	}
}
